### PR TITLE
Add touched class to control groups

### PR DESCRIPTION
**Pull request by istrau3**
This is for 
MarvelousSoftware/marvelous-aurelia-forms#2

I added a touched property for each field that triggers a class on the group if the control has been blurred at least once.

### CODE REVIEW

**Comment by damiankaminski** [comment]
Could you change the class name to `m-touched`? That's the convention - it should prevent from name collisions with other libraries. Once you do that I'll merge.

**Comment by istrau3** [comment]
@damiankaminski Ok, I also just realized that I added to the wrong method. Should have added to onBlured instead of onFocused. I will change that as well. Thanks.

**Comment by damiankaminski** [comment]
Oops, I didn't notice it as well. :)

**Comment by istrau3** [comment]
@damiankaminski Ok, I made the changes. 

Note: I didn't build the project (wasn't really sure how).

**Comment by damiankaminski** [comment]
@istrau3 No worries, I'll check if it works correctly.

For the sake of reference: to build the project you have to pull `marvelous-aurelia-core` repository. It needs to be in the same directory as `marvelous-aurelia-forms`. Then `npm install`, `jspm install`, `tsd install`, `gulp watch` first in the core project and then in forms. To watch how your changes behaves you can pull `marvelous-aurelia-docs`. It holds http://marvelous.software/docs.html site. Installation process is same as for libraries.

I should probably describe this process better on the README page. Will do in the near future.

**Pull request merged**
